### ISSUE TITLE
compilar main_windows ? 

### ISSUE THREAD

**Issue by diegocrzt** [aVolpe/tesis#1]
Por qué #@~% tengo que compilar main_windows para ver con otro visor de pdf ?

**Comment by aVolpe** [comment]
Buen día @diegocrzt:

Reproducir videos en un pdf es un tema complicado, cuando se hizo esta tesis, solamente lo soportaban Okular y Adobe Reader, pero de diferente manera.
- Para okular, se usa el paquete `media9`, que tiene la directiva `movie`, y que embede el video con el PDF, haciendo que el archivo pdf sea grande.
- Para otros (adobe reader) se usa el paquete `multimedia`, que tiene la directiva `includemedia`, que usa los videos externos y los reproduce.

Ambos tex son iguales, solamente que definen dos variables, que permiten que se incluya o el archivo [macro_linux](https://github.com/aVolpe/tesis/blob/master/presentacion/macro_linux.tex) o el [macro_windows](https://github.com/aVolpe/tesis/blob/master/presentacion/macro_windows.tex).

En los archivos, se ve la linea [238](https://github.com/aVolpe/tesis/blob/master/presentacion/main_linux.tex#L238), que es donde es declaran las variables necesarias para que se incluya uno u otra macro.

Ahora mismo estoy viendo para crear una imagen docker que pueda compilar estos documentos, por que mi curriculum también esta en latex y no tengo espacio en mi disco principal para instalar los paquetes para probar.

Otro motivo, es que la versión de Windows, lanza en un reproductor externo y la apariencia no es tan buena, con `media9` sale mucho mejor, pero solo logramos hacer funcionar en Okular.
